// Review screen: recording list, and the recording page
V.review=function(){if(openRec){const r=rec(openRec);if(r)return recView(r);openRec=null}
 return `<h2>Review</h2><div class="card"><h3 style="margin-top:0">Add a recording</h3><div class="form"><input id="rt" class="wide" placeholder="Title"><input id="rd" type="date" value="${today()}"><select id="rp">${pOpts()}</select></div><div class="form" style="margin-top:10px"><input id="ru" type="url" placeholder="Video link (YouTube, Drive...)"><input id="rf" type="file" accept="video/*"></div><div class="lbl">Tags</div>${tagPicker('rtg',[])}<button class="b full" onclick="addRec()">Add recording</button></div>
 ${db.recs.slice().reverse().map(r=>{const open=(r.notes||[]).filter(n=>n.type==='needs'&&!n.done).length;return `<div class="card item" onclick="openRec='${r.id}';render()" style="cursor:pointer">${ytId(r.url)?`<img class="lthumb" src="https://i.ytimg.com/vi/${ytId(r.url)}/mqdefault.jpg" alt="">`:''}<div class="grow"><b>${E(r.title)}</b><div class="mu">${fmtDate(r.date)} &middot; ${E(pname(r.piece))}</div><div class="mu">${pl((r.notes||[]).length,'note')}${open?` &middot; ${open} to fix`:''}${r.rating?` &middot; ${r.rating} / 10`:''}</div>${chipLine(r.tags,8)}</div></div>`}).join('')||'<div class="mu">No recordings yet.</div>'}`};

const cancelN='<button class="b s" onclick="ed=null;refreshNotes()">Cancel</button>';
function recView(r){return `<a href="#" class="back" onclick="openRec=null;ed=null;render();return false">&lsaquo; All recordings</a>
 ${recHead(r)}
 ${playerHtml(r,files[r.id])}
 <div id="notes-area">${notesHtml(r)}</div>`}
function notesHtml(r){const en=(r.notes||[]).find(n=>ed==='n:'+n.id)||null,adding=ed==='n:new'||!!en,so=v=>en&&en.type===v?' selected':'',notes=(r.notes||[]).slice().sort((a,b)=>a.t-b.t),open=notes.filter(n=>n.type==='needs'&&!n.done).length;
 return `<div class="row between" style="margin:26px 0 12px"><h3 style="margin:0">Notes (${notes.length})${open?` <span class="bad" style="text-transform:none;letter-spacing:0">${open} to fix</span>`:''}</h3>${adding?'':`<button class="b sm" onclick="ed='n:new';refreshNotes()">Add note</button>`}</div>
 ${adding?`<div class="card" id="nform"><h3 style="margin-top:0">${en?'Edit note':'New note'}</h3><div class="row"><input id="nt" placeholder="Time (1:32)" value="${en?fmt(en.t):''}" style="max-width:110px;flex:none"><button class="b s" onclick="grab()">Use video time</button>
 <select id="ny"><option value="good"${so('good')}>Good</option><option value="needs"${en?so('needs'):' selected'}>Needs work</option><option value="q"${so('q')}>Question</option></select></div>
 <div class="form" style="margin:10px 0"><input id="ns" placeholder="Section (bars 17-24)" value="${E(en?en.sec:'')}"><input id="ng" list="tl2" placeholder="Technique tag" value="${E(en?en.tag:'')}"><datalist id="tl2">${db.tags.map(t=>`<option>${E(t)}`).join('')}</datalist></div>
 <textarea id="nx" placeholder="What happened">${E(en?en.text:'')}</textarea>
 <div class="row"><select id="nr"><option value="">Attach resource</option>${db.res.map(x=>`<option value="${x.id}"${en&&en.res===x.id?' selected':''}>${E(x.t)}</option>`).join('')}</select><button class="b" onclick="addNote('${r.id}')">${en?'Update note':'Save note'}</button>${cancelN}</div></div>`:''}
 ${notes.map(n=>{const rs=db.res.find(x=>x.id===n.res),needs=n.type==='needs';return `<div class="card note ${n.type}${n.done?' isdone':''}"><div class="row"><a href="#" class="ts" onclick="seek(${n.t});return false">${fmt(n.t)}</a><b class="${n.type==='good'?'good':needs?'bad':''}">${n.type==='good'?'Good':needs?'Needs work':'Question'}</b>${n.done?'<span class="tag">Done</span>':''}${n.sec?`<span class="tag">${E(n.sec)}</span>`:''}${n.tag?`<span class="tag">${E(n.tag)}</span>`:''}</div>
 <div class="ntext">${E(n.text)}</div>${rs?`<div class="mu" style="margin-top:6px">Resource: ${/^https?:/.test(rs.u)?`<a href="${E(rs.u)}" target="_blank" rel="noopener">${E(rs.t)}</a>`:E(rs.t)}</div>`:''}
 <div class="row nacts">${needs?(n.done?`<button class="b s sm" onclick="setDone('${r.id}','${n.id}',false)">Reopen</button>`:`<button class="b sm" onclick="setDone('${r.id}','${n.id}',true)">Mark done</button>`):''}<button class="x" style="color:var(--ac)" onclick="ed='n:${n.id}';refreshNotes()">Edit</button><button class="x" onclick="delNote('${r.id}','${n.id}')">Delete</button></div></div>`}).join('')||(adding?'':'<div class="mu">No notes yet. Tap Add note while you watch.</div>')}`}
function tUrl(u,t){try{const x=new URL(u);if(/youtu/.test(x.host)){x.searchParams.set('t',t+'s');return x.href}x.hash='t='+t;return x.href}catch(e){return u}}
function recHead(r){if(ed==='r:'+r.id)return `<div class="card"><h3 style="margin-top:0">Edit details</h3><div class="form"><input id="et" class="wide" value="${E(r.title)}" placeholder="Title"><input id="edt" type="date" value="${r.date}"><select id="ep">${pOpts(r.piece)}</select><input id="eu" class="wide" type="url" value="${E(r.url)}" placeholder="Video link"></div><div class="lbl">Tags</div>${tagPicker('etg',r.tags)}<div class="row between" style="margin-top:14px"><span class="row"><button class="b" onclick="saveRec('${r.id}')">Save</button>${cancel}</span><button class="x" onclick="delRec('${r.id}')">Delete recording</button></div></div>`;
 return `<div class="rhead"><div class="grow"><h2 style="margin:0 0 6px">${E(r.title)}</h2><div class="mu">${fmtDate(r.date)} &middot; ${E(pname(r.piece))}</div><div class="row" style="margin-top:10px"><span class="mu">Rating</span><select onchange="setRating('${r.id}',this.value)" style="min-height:38px;padding:6px 36px 6px 12px">${Array.from({length:11},(_,i)=>`<option value="${i}"${(r.rating||0)===i?' selected':''}>${i?i+' / 10':'Not rated'}</option>`).join('')}</select></div>${chipLine(r.tags,10)}</div><button class="b s sm" onclick="ed='r:${r.id}';render()">Edit</button></div>`}
