// Review screen and recording detail
V.review=function(){if(openRec)return recView(db.recs.find(r=>r.id===openRec));
 return `<h2>Review</h2><div class="card"><h3 style="margin-top:0">Add a recording</h3><div class="form"><input id="rt" class="wide" placeholder="Title"><input id="rd" type="date" value="${today()}"><select id="rp">${pOpts()}</select></div>
 <div class="form" style="margin-top:10px"><input id="ru" type="url" placeholder="Video link (YouTube, Drive...)"><input id="rf" type="file" accept="video/*"></div><div class="lbl">Tags</div>${tagPicker('rtg',[])}<button class="b full" onclick="addRec()">Add recording</button></div>
 ${db.recs.slice().reverse().map(r=>`<div class="card row" onclick="openRec='${r.id}';render()" style="cursor:pointer"><div><b>${E(r.title)}</b><div class="mu">${r.date} - ${E(pname(r.piece))} - ${(r.notes||[]).length} notes</div>${chipLine(r.tags,8)}</div><span class="mu" style="margin-left:auto">${r.rating?r.rating+'/5':''}</span></div>`).join('')}`};
function recView(r){const f=files[r.id],tags=db.tags,en=(r.notes||[]).find(n=>ed==='n:'+n.id)||null,so=(v)=>en&&en.type===v?' selected':'';
 const link=r.url?`<a href="${E(r.url)}" target="_blank" rel="noopener">Open video link</a>`:'';
 return `<button class="b s" onclick="openRec=null;ed=null;render()">Back</button>${recHead(r,link)}
 ${playerHtml(r,f)}
 <div class="card" style="margin-top:12px"><h3 style="margin-top:0">${en?'Edit note':'Add note'}</h3><div class="row"><input id="nt" placeholder="Time (1:32)" value="${en?fmt(en.t):''}" style="max-width:110px;flex:none"><button class="b s" onclick="grab()">Use video time</button>
 <select id="ny"><option value="good"${so('good')}>Good</option><option value="needs"${so('needs')}>Needs work</option><option value="q"${so('q')}>Question</option></select></div>
 <div class="form" style="margin:10px 0"><input id="ns" placeholder="Section (bars 17-24)" value="${E(en?en.sec:'')}"><input id="ng" list="tl2" placeholder="Technique tag" value="${E(en?en.tag:'')}"><datalist id="tl2">${tags.map(t=>`<option>${t}`).join('')}</datalist></div>
 <textarea id="nx" placeholder="What happened">${E(en?en.text:'')}</textarea><div class="row"><select id="nr"><option value="">Attach resource</option>${db.res.map(x=>`<option value="${x.id}"${en&&en.res===x.id?' selected':''}>${E(x.t)}</option>`).join('')}</select><button class="b" onclick="addNote('${r.id}')">${en?'Update note':'Save note'}</button>${en?'<button class="b s" onclick="ed=null;render()">Cancel</button>':''}</div></div>
 ${(r.notes||[]).slice().sort((a,b)=>a.t-b.t).map(n=>{const rs=db.res.find(x=>x.id===n.res);return `<div class="card"><div class="row"><b class="${n.type==='good'?'good':n.type==='needs'?'bad':''}">${n.type==='good'?'Good':n.type==='needs'?'Needs work':'Question'}</b>
 <a href="#" onclick="seek(${n.t});return false">${fmt(n.t)}</a>
 ${n.sec?`<span class="tag">${E(n.sec)}</span>`:''}${n.tag?`<span class="tag">${E(n.tag)}</span>`:''}<span style="margin-left:auto"><button class="x" style="color:var(--ac)" onclick="ed='n:${n.id}';render()">Edit</button><button class="x" onclick="delNote('${r.id}','${n.id}')">Delete</button></span></div>
 <div>${E(n.text)}</div>${rs?`<div class="mu">Resource: ${/^https?:/.test(rs.u)?`<a href="${E(rs.u)}" target="_blank" rel="noopener">${E(rs.t)}</a>`:E(rs.t)}</div>`:''}</div>`}).join('')}
 <div class="card"><h3 style="margin-top:0">Summary</h3><div class="mu">What went well</div><textarea id="sg">${E(r.good)}</textarea>
 <div class="mu">What to fix (one per line; optional "section: text" feeds Focus next)</div><textarea id="sf">${E(r.fix)}</textarea>
 <div class="row"><select id="sr">${[0,1,2,3,4,5].map(i=>`<option value="${i}"${r.rating==i?' selected':''}>${i?i+' / 5':'No rating'}</option>`).join('')}</select><button class="b" onclick="saveSum('${r.id}')">Save summary</button><button class="x" onclick="delRec('${r.id}')">Delete recording</button></div></div>`}
function tUrl(u,t){try{const x=new URL(u);if(/youtu/.test(x.host)){x.searchParams.set('t',t+'s');return x.href}x.hash='t='+t;return x.href}catch(e){return u}}
function recHead(r,link){if(ed==='r:'+r.id)return `<div class="card" style="margin-top:12px"><div class="form"><input id="et" class="wide" value="${E(r.title)}" placeholder="Title"><input id="edt" type="date" value="${r.date}"><select id="ep">${pOpts(r.piece)}</select><input id="eu" class="wide" type="url" value="${E(r.url)}" placeholder="Video link"></div><div class="lbl">Tags</div>${tagPicker('etg',r.tags)}<div class="row" style="margin-top:12px"><button class="b" onclick="saveRec('${r.id}')">Save</button>${cancel}</div></div>`;
 return `<h2 style="margin-top:12px">${E(r.title)}</h2><div class="row mu"><span>${r.date} - ${E(pname(r.piece))}</span>${link}<button class="x" style="color:var(--ac)" onclick="ed='r:${r.id}';render()">Edit details</button></div>${chipLine(r.tags,8)}`}
