// Review screen: recording list, and the recording page (view mode by default)
V.review=function(){if(openRec){const r=rec(openRec);if(r)return recView(r);openRec=null}
 return `<h2>Review</h2><div class="card"><h3 style="margin-top:0">Add a recording</h3><div class="form"><input id="rt" class="wide" placeholder="Title"><input id="rd" type="date" value="${today()}"><select id="rp">${pOpts()}</select></div><div class="form" style="margin-top:10px"><input id="ru" type="url" placeholder="Video link (YouTube, Drive...)"><input id="rf" type="file" accept="video/*"></div><div class="lbl">Tags</div>${tagPicker('rtg',[])}<button class="b full" onclick="addRec()">Add recording</button></div>
 ${db.recs.slice().reverse().map(r=>`<div class="card item" onclick="openRec='${r.id}';render()" style="cursor:pointer">${ytId(r.url)?`<img class="lthumb" src="https://i.ytimg.com/vi/${ytId(r.url)}/mqdefault.jpg" alt="">`:''}<div class="grow"><b>${E(r.title)}</b><div class="mu">${fmtDate(r.date)} &middot; ${E(pname(r.piece))} &middot; ${(r.notes||[]).length} notes</div>${chipLine(r.tags,8)}</div><span class="mu">${r.rating?r.rating+' / 5':''}</span></div>`).join('')||'<div class="mu">No recordings yet.</div>'}`};

function recView(r){const f=files[r.id],en=(r.notes||[]).find(n=>ed==='n:'+n.id)||null,adding=ed==='n:new'||!!en,so=v=>en&&en.type===v?' selected':'',notes=(r.notes||[]).slice().sort((a,b)=>a.t-b.t);
 const fix=(r.fix||'').split('\n').map(x=>x.trim()).filter(Boolean);
 return `<a href="#" class="back" onclick="openRec=null;ed=null;render();return false">&lsaquo; All recordings</a>
 ${recHead(r)}
 ${playerHtml(r,f)}
 <div class="row between" style="margin:26px 0 12px"><h3 style="margin:0">Notes (${notes.length})</h3>${adding?'':`<button class="b sm" onclick="ed='n:new';render()">Add note</button>`}</div>
 ${adding?`<div class="card" id="nform"><h3 style="margin-top:0">${en?'Edit note':'New note'}</h3><div class="row"><input id="nt" placeholder="Time (1:32)" value="${en?fmt(en.t):''}" style="max-width:110px;flex:none"><button class="b s" onclick="grab()">Use video time</button>
 <select id="ny"><option value="good"${so('good')}>Good</option><option value="needs"${so('needs')}>Needs work</option><option value="q"${so('q')}>Question</option></select></div>
 <div class="form" style="margin:10px 0"><input id="ns" placeholder="Section (bars 17-24)" value="${E(en?en.sec:'')}"><input id="ng" list="tl2" placeholder="Technique tag" value="${E(en?en.tag:'')}"><datalist id="tl2">${db.tags.map(t=>`<option>${E(t)}`).join('')}</datalist></div>
 <textarea id="nx" placeholder="What happened">${E(en?en.text:'')}</textarea>
 <div class="row"><select id="nr"><option value="">Attach resource</option>${db.res.map(x=>`<option value="${x.id}"${en&&en.res===x.id?' selected':''}>${E(x.t)}</option>`).join('')}</select><button class="b" onclick="addNote('${r.id}')">${en?'Update note':'Save note'}</button>${cancel}</div></div>`:''}
 ${notes.map(n=>{const rs=db.res.find(x=>x.id===n.res);return `<div class="card note ${n.type}"><div class="row between"><div class="row"><a href="#" class="ts" onclick="seek(${n.t});return false">${fmt(n.t)}</a><b class="${n.type==='good'?'good':n.type==='needs'?'bad':''}">${n.type==='good'?'Good':n.type==='needs'?'Needs work':'Question'}</b>${n.sec?`<span class="tag">${E(n.sec)}</span>`:''}${n.tag?`<span class="tag">${E(n.tag)}</span>`:''}</div><span style="white-space:nowrap"><button class="x" style="color:var(--ac)" onclick="ed='n:${n.id}';render()">Edit</button><button class="x" onclick="delNote('${r.id}','${n.id}')">Delete</button></span></div>
 <div class="ntext">${E(n.text)}</div>${rs?`<div class="mu" style="margin-top:6px">Resource: ${/^https?:/.test(rs.u)?`<a href="${E(rs.u)}" target="_blank" rel="noopener">${E(rs.t)}</a>`:E(rs.t)}</div>`:''}</div>`}).join('')||(adding?'':'<div class="mu">No notes yet. Tap Add note while you watch.</div>')}
 <h3 style="margin:26px 0 12px">Summary</h3>
 ${ed==='s:'+r.id?`<div class="card"><div class="lbl" style="margin-top:0">What went well</div><textarea id="sg">${E(r.good)}</textarea><div class="lbl" style="margin-top:0">What to fix</div><div class="mu" style="margin-bottom:8px">One per line. Start a line with "section: " to tie it to a spot in Focus next.</div><textarea id="sf">${E(r.fix)}</textarea>
 <div class="row"><select id="sr">${[0,1,2,3,4,5].map(i=>`<option value="${i}"${r.rating==i?' selected':''}>${i?i+' / 5':'No rating'}</option>`).join('')}</select><button class="b" onclick="saveSum('${r.id}')">Save summary</button>${cancel}</div></div>`
 :`<div class="card"><div class="row between"><span class="mu">Rating: ${r.rating?r.rating+' / 5':'not rated'}</span><button class="x" style="color:var(--ac)" onclick="ed='s:${r.id}';render()">Edit</button></div>
 <div class="lbl">What went well</div>${r.good?`<div class="ntext">${E(r.good)}</div>`:'<div class="mu">Nothing added yet</div>'}
 <div class="lbl">What to fix</div>${fix.length?fix.map(l=>`<div class="ntext" style="padding:2px 0">- ${E(l)}</div>`).join(''):'<div class="mu">Nothing added yet</div>'}</div>`}`}
function tUrl(u,t){try{const x=new URL(u);if(/youtu/.test(x.host)){x.searchParams.set('t',t+'s');return x.href}x.hash='t='+t;return x.href}catch(e){return u}}
function recHead(r){if(ed==='r:'+r.id)return `<div class="card"><h3 style="margin-top:0">Edit details</h3><div class="form"><input id="et" class="wide" value="${E(r.title)}" placeholder="Title"><input id="edt" type="date" value="${r.date}"><select id="ep">${pOpts(r.piece)}</select><input id="eu" class="wide" type="url" value="${E(r.url)}" placeholder="Video link"></div><div class="lbl">Tags</div>${tagPicker('etg',r.tags)}<div class="row between" style="margin-top:14px"><span class="row"><button class="b" onclick="saveRec('${r.id}')">Save</button>${cancel}</span><button class="x" onclick="delRec('${r.id}')">Delete recording</button></div></div>`;
 return `<div class="rhead"><div class="grow"><h2 style="margin:0 0 6px">${E(r.title)}</h2><div class="mu">${fmtDate(r.date)} &middot; ${E(pname(r.piece))}</div>${chipLine(r.tags,10)}</div><button class="b s sm" onclick="ed='r:${r.id}';render()">Edit</button></div>`}
