// Today screen
V.today=function(){const s=streaks(),dow=new Date().getDay(),plan=db.cal[today()]||[],f=openNotes(),t=db.timer;
 return `<h2>Today</h2><div class="card hero"><div class="row"><div><div class="big">${s.cur}</div><div class="mu">day streak (best ${s.best})</div></div><div style="margin-left:auto" class="${s.on?'good':'mu'}">${s.on?'Practiced today':'Not practiced yet'}</div></div></div>
 <div class="card timer"><h3 style="margin-top:0">Practice session</h3><div class="big" id="tm">${hms(el())}</div><div class="row" style="margin-top:8px">
 ${!t?'<button class="b" onclick="tm(\'start\')">Start</button>':t.run?'<button class="b" onclick="tm(\'pause\')">Pause</button>':'<button class="b" onclick="tm(\'resume\')">Resume</button>'}
 ${t?'<button class="b s" onclick="tm(\'stop\')">Stop and save</button><button class="x" onclick="el()<6e4?tm(\'discard\'):ask(\'Discard session\',\'This session is thrown away and no time is saved.\',\'Discard\',()=>tm(\'discard\'),1)">Discard</button>':''}</div><div class="mu" style="margin-top:6px">Only active time is logged. Today: ${db.log[today()]||0} min</div></div>
 <div class="card"><h3 style="margin-top:0">Today's plan (${DAYS[dow]})</h3>${plan.length?plan.map(p=>{const k=today()+'#'+p.id;return `<label class="chk"><input type="checkbox" ${db.done[k]?'checked':''} onchange="db.done['${k}']=this.checked;save();render()"><span>${E(p.text)}${p.min?' <span class="mu">'+p.min+' min</span>':''}</span></label>`}).join(''):'<span class="mu">Nothing planned. Add items in Calendar.</span>'}</div>
 <h3>Focus next${f.length?' ('+f.length+' open)':''}</h3>${f.length?f.slice(0,5).map(focusCard).join('')+(f.length>5?`<div class="mu">${f.length-5} more in Review.</div>`:''):'<div class="card mu">Nothing open. Mark a note as Needs work while you review.</div>'}`};
function focusCard({r,n}){return `<div class="card note needs"><div class="mu">${E(pname(r.piece))} &middot; ${E(r.title)}</div><div class="row" style="margin:8px 0 0"><span class="ts">${fmt(n.t)}</span>${n.sec?`<span class="tag">${E(n.sec)}</span>`:''}${n.tag?`<span class="tag">${E(n.tag)}</span>`:''}</div>
 <div class="ntext">${E(n.text)}</div><div class="row nacts"><button class="b sm" onclick="setDone('${r.id}','${n.id}',true)">Mark done</button><button class="b s sm" onclick="openRecording('${r.id}')">Open</button></div></div>`}
